const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brnad: "Nike",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "adidias Slim shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 110,
      countInStock: 20,
      brnad: "adidas",
      rating: "4",
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "lacosta Slim shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 200,
      countInStock: 0,
      brnad: "Nike",
      rating: "3.5",
      numReviews: 20,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 150,
      countInStock: 10,
      brnad: "Nike",
      rating: "4",
      numReviews: 5,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "puma Slim pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 67,
      countInStock: 5,
      brnad: "puma",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "adidas Slim pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 89,
      countInStock: 12,
      brnad: "adidas",
      rating: "4",
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
